# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 22:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certifications', '0003_auto_20170811_0107'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('expiration_date', models.DateField(verbose_name='Expiration date')),
                ('remind_at_date', models.DateField(blank=True, null=True, verbose_name='Remind at')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_certifications', to='certifications.Certification', verbose_name='Certification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': "User's certification",
                'verbose_name_plural': "User's certifications",
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='UserExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date_of_pass', models.DateField(verbose_name='Date of pass')),
                ('remind_at_date', models.DateField(blank=True, null=True, verbose_name='Remind at')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_exams', to='certifications.Exam', verbose_name='Exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cert_exams', to='cert_remainder.UserCertification', verbose_name='User certification')),
            ],
            options={
                'verbose_name': "User's exam",
                'verbose_name_plural': "User's exams",
                'ordering': ('created',),
            },
        ),
    ]
