# Generated by Django 2.0.5 on 2018-05-29 00:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0003_auto_20170811_0107'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cert_remainder', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercertification',
            unique_together={('user', 'certification')},
        ),
        migrations.AlterUniqueTogether(
            name='userexam',
            unique_together={('user', 'exam', 'user_certification')},
        ),
    ]
