# Generated by Django 2.2.6 on 2019-10-15 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certifications', '0004_auto_20180619_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('main_url', models.URLField(help_text='The main page, from which parsing should be started', verbose_name='Main URL')),
                ('base_url', models.URLField(blank=True, help_text='The url, which be added to certification paths.', verbose_name='Base url')),
                ('parser_class_id', models.CharField(max_length=30, unique=True, verbose_name='Parser ID')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certifications.Vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Parser config',
                'verbose_name_plural': 'Parser configs',
                'ordering': ('created',),
            },
        ),
    ]
