# Generated by Django 2.2.6 on 2019-10-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0002_parserconfig_certification_title_css_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parserconfig',
            name='certification_title_css_class',
        ),
        migrations.AddField(
            model_name='parserconfig',
            name='certification_title_css_selector',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Certification title css selector'),
        ),
    ]
