# Generated by Django 2.2.6 on 2019-10-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0003_auto_20191025_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserconfig',
            name='certification_description_css_selector',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Certification description css selector'),
        ),
        migrations.AddField(
            model_name='parserconfig',
            name='certifications_link_css_selector',
            field=models.CharField(blank=True, default='', help_text='Selector to parse all links from main_url', max_length=255, verbose_name='Certifications link css selector'),
        ),
        migrations.AddField(
            model_name='parserconfig',
            name='exam_description_css_selector',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Exam description css selector'),
        ),
        migrations.AddField(
            model_name='parserconfig',
            name='exam_title_css_selector',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Exam title css selector'),
        ),
    ]
