# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users', verbose_name='Profile image'),
        ),
    ]
