# Generated by Django 2.2.1 on 2019-05-24 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190523_0520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'ordering': ('created',), 'verbose_name': 'Password reset token', 'verbose_name_plural': 'Password reset tokens'},
        ),
    ]
