# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Exam number'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='title',
            field=models.CharField(max_length=120, unique=True, verbose_name='Title'),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set([('title', 'number')]),
        ),
    ]
