# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_auto_20170811_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Certification number'),
        ),
    ]
